server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://azuobietmffivx:9f96f6c556fe3251498dd8aed881bb884886f2a705f776d6ddda69662c2e4428@ec2-52-4-111-46.compute-1.amazonaws.com:5432/da9tj6318t3tlq
    username: azuobietmffivx
    password: 9f96f6c556fe3251498dd8aed881bb884886f2a705f776d6ddda69662c2e4428
  jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true
      hibernate:
        ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander Universidades / Backend